name: Create Security Group using GH Actions 
on:
    push:
        branches: [main]
jobs:
    JobForClone:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
            - name: Creating Security Groups
              run: |
               aws ec2 create-security-group \
               --group-name sgsumeetsghactions \
               --description "test description" \
               --vpc-id vpc-08e5bc89ab4518ee3